import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"CHATXGPT_robot") 
SUDO=os.environ.get("SUDO","6542673293")
BOT_NAME = os.environ.get("BOT_NAME","CHATGPT BOT")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/50a0e3e2f5b42a1542321.jpg")
STKR = os.environ.get("STKR","CAACAgIAAxkBAAEDAi9kpoZsScowUfZL9z6RC-NFzkR4swACFzMAAllsMEkhLDB782R9GS8E")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","ZenBotX")
OWNER_USERNAME = os.environ.get("OWNER_USERNAME","NoobZen")
SUDO=os.environ.get("SUDO","6542673293")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","QuirkySquad")
